### ISSUE TITLE
Could you add a LICENSE

### ISSUE THREAD

**Issue by sanchoooo** [korovkin/limiter#11]
The code is missing a LICENSE file indicating what license it's released under.
https://choosealicense.com/no-permission/
"When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you."

**Comment by thunderstorm99** [comment]
I second that, please add a license to this project. it shouldn't be too much of a task.

**Comment by eyalkenig** [comment]
It's a bummer we wouldn't be able to use this project due to missing license...

**Comment by korovkin** [comment]
damn, i just noticed that
i will add a license now

**Comment by korovkin** [comment]
adding it now, please let me know if it works
