### ISSUE TITLE
some jobs get repeated multiple times when execution starts

### ISSUE THREAD

**Issue by NinoFoxx** [korovkin/limiter#13]
I'm fetching some links from a slow server so I started using limiter but it is repeating the first few jobs...  it normalizes afterwards though.

I've used this lib before and this never happened...

go version: `go1.15.2 windows/amd64`

lib version: the latest one. I deleted the lib and ran `go get` again to make sure.

here's a few screenshots:

![image](https://user-images.githubusercontent.com/8485761/94350585-e7579a00-0025-11eb-88a2-14d7ee760e09.png)
notice how it is **not** repeated on the wordlist:
![image](https://user-images.githubusercontent.com/8485761/94350496-33eea580-0025-11eb-9c00-24fce85daacb.png)

here's part of the code:

```
limit := limiter.NewConcurrencyLimiter(10)
for scanner.Scan() { // <- reading lines from the wordlist file
    limit.Execute(func() {
        url := baseURL + scanner.Text()
        filename, _ := fetchLink(url)
        output := fmt.Sprintf("%v > %v\n", url, filename)
        fmt.Printf(output)
    })
}
limit.Wait()
```

I also tried building a `var jobs []string` on the scanner loop and moving the limiter execution to another for loop (`for _, job := range jobs`) but it didn't solve the issue.

The only workaround I can think of is keeping a variable with finished jobs and checking if X job has been ran already, but the lib shouldn't do what it's doing either way..

I'd love to help and try to fix the lib myself, but I'm still a beginner in Go, so I don't think I'm able to help.

**Comment by NinoFoxx** [comment]
> The only workaround I can think of is keeping a variable with finished jobs and checking if X job has been ran already

nope. didn't work.

**Comment by NinoFoxx** [comment]
not even this very over-complicated workaround did the trick....

```
limit := limiter.NewConcurrencyLimiter(20)
var executed []string
var count int
rand.Seed(time.Now().UnixNano())

for scanner.Scan() {
	limit.Execute(func() {
		text := scanner.Text()
		if count < 10 {
			time.Sleep(time.Second * time.Duration(rand.Intn(5)))
			count++
			if sliceContainsString(executed, text) {
				return
			}
			executed = append(executed, text)
		}
		url := baseURL + text
		filename, _ := fetchLink(url)
		output := fmt.Sprintf("%v > %v\n", url, filename)
		fmt.Printf(output)
	})
}
limit.Wait()

func sliceContainsString(slice []string, item string) bool {
	for _, a := range slice {
		if a == item {
			return true
		}
	}
	return false
}
```

**Comment by inkeliz** [comment]
I think the issue is to call `scanner.Text()` inside the goroutine, since there's no garantee that it will run before the next `scanner.Scan()`.

-----------

Could you try use:

```
limit := limiter.NewConcurrencyLimiter(10)
for scanner.Scan() { // <- reading lines from the wordlist file

    url := baseURL + scanner.Text() // << Sets the url value, before the goroutine.

    limit.Execute(func() {
        filename, _ := fetchLink(url)
        output := fmt.Sprintf("%v > %v\n", url, filename)
        fmt.Printf(output)
    })
}
limit.Wait()
```

The `scanner.Text()` returns the "the most recent token generated by a call to Scan" (https://cs.opensource.google/go/go/+/refs/tags/go1.16.7:src/bufio/scan.go;l=112). So, I think it's a "race-condition", kind of. The `for` is calling `scanner.Scan()` before the `scanner.Text()`. When the gouroutine executes, it may get the same text, since it calls `scanner.Text()` at same time.

**Comment by NinoFoxx** [comment]
oh, that actually makes total sense. I haven't thought of that.  :)

my project has been rewritten from scratch since then, using Redis instead of storing the link codes into files but I just tested the old code and it seems to fix the issue.

thank you @Inkeliz!
