### ISSUE TITLE
question: how to find optimal value for concurrentlimit?

### ISSUE THREAD

**Issue by tuananh** [korovkin/limiter#23]
I'm using the default DefaultConcurrencyLimitIO (4) but I find it's a lot faster for my case when I set it to higher value.

How should I find the optimal value for this?

**Comment by korovkintaptap** [comment]
Well it’s a trade of between making your IO faster and more concurrent vs making sure you don’t overload the target (DB / Service / Networking layer) 



It’s something that only you can decide given your usage pattern. 
And obviously how many other instances of concurrently there are running on your process and serve
