### ISSUE TITLE
how about make the called goroutine accept variable types of arguments

### ISSUE THREAD

**Issue by RocFang** [korovkin/limiter#3]
hello, @korovkin , 
thanks for your work first.
how about make the called goroutine accept variable types and number of arguments, so this package can be used more extensive.

**Comment by korovkin** [comment]
I am not sure I understood the request. 

Could you please share a code example of what would you like the library to support?

**Comment by RocFang** [comment]
thans for your reply:)
for example, my job function may take one parameter, like below:
```
func function(a TypeA) {
    ....
}
```

or may take two parameters, like below:
```
func function(a TypeA, b TypeB) {
}
```

it seems i can't calling the function as job for the paramter types when i call limit.Execute.

**Comment by korovkin** [comment]
the above is possible, it would look something like this: 

```
limit := NewConcurrencyLimiter(10)
for i := 0; i < 1000; i++ {
  	limit.Execute(func() {
  		function(a, b)
  	})
}
limit.Wait()
```

the Execute function takes a binded function as a parameter, you can choose and pick what values that function would reference (what will be captured by that scope)

**Comment by RocFang** [comment]
@korovkin  sorry for my missunderstanding.
I didn't notice  that the job is a binded function:)

Thanks again.
