### ISSUE TITLE
How to use var i from for loop in executing job

### ISSUE THREAD

**Issue by atecey** [korovkin/limiter#4]
I'm using your package to limit the number of goroutines. I'm using it in a for loop as below. I'm using the variable i to access values from an array for processing. It seems to be that based on the value passed into the concurrency limiter the value of i will be the same. i.e. if the value passed in is 5 the first five iterations of the loop i will = 5. After that it increments accordingly. 
```
func runConcurrently() {
	limit := limiter.NewConcurrencyLimiter(10)
	var count = len(objects)
	for i := 0; i < count; i++ {
		limit.Execute(func() {
			fmt.Println(i)
                        fmt.Println(array[i].Name)
                }
        }
        limit.Wait()
}
```

How do I use this package so that I can set the NewConcurrencyLimiter to any value and i increment from 0 to x?

**Comment by linture** [comment]
i will definitely be the same same every goroutine operates can touch it. You may learn more about concurrent programming. The right way to get increasing i may be this
`func runConcurrently() {
	limit := limiter.NewConcurrencyLimiter(10)
	var count = len(objects)
	for i := 0; i < count; i++ {
                 value := i
		limit.Execute(func() {
			fmt.Println(value)
                        fmt.Println(array[value].Name)
                }
        }
        limit.Wait()
}`
